### ISSUE TITLE
Color distinction between normal html tags and component tags

### ISSUE THREAD

**Issue by la-magbanua** [enkia/tokyo-night-vscode-theme#13]
My eyes are forever grateful for the theme you made, It's my daily driver. I just wish we could have this color distinction between a component and a normal html tag. Makes it so much easier to scan with the eyes which is which especially when you're writing tons of components together with normal html tags, thanks! 

![snippet](https://user-images.githubusercontent.com/56512548/96954115-50e39f00-1525-11eb-8aaf-5601e153b118.PNG)

**Comment by enkia** [comment]
<img width="489" alt="image" src="https://user-images.githubusercontent.com/255730/97032204-707fc500-152f-11eb-80a2-b1ba3677b864.png">

Would this be enough of a distinction?

**Comment by la-magbanua** [comment]
I really like the subtle use of colors here! Maybe just a shade more or two and it's perfect!

**Comment by enkia** [comment]
Thanks for the suggestion @la-magbanua!

See cb56e1935faa3bef492648716e84b2bd51e24018

If you prefer a different color, re-open this and I'll paste in some code you can use in your own settings.json.

**Comment by enkia** [comment]
Thanks for the suggestion @la-magbanua!

See cb56e1935faa3bef492648716e84b2bd51e24018

If you prefer a different color, re-open this and I'll paste in some code you can use in your own settings.json.
