### ISSUE TITLE
Provide Color Palette for Porting Purpose

### ISSUE THREAD

**Issue by fitrh** [enkia/tokyo-night-vscode-theme#17]
I love this color scheme, my vim, alacritty, even my tmux, i use this color scheme, we can open the JSON file to see all the colors, but i think it's a good idea to provide something like color palette guideline so another contributor can easily porting this theme for other platform.

**Comment by enkia** [comment]
Thanks @fitrh 

I'll try to have a palette available before the holidays are over.

**Comment by enkia** [comment]
About half way done... Need to finalize/proof read the dark, and do all of the light colors. 

***Tokyo Night / Tokyo Night Storm Color Palette***

| Color      | Hex                                                          | Use                                           |
| ---------- | ------------------------------------------------------------ | --------------------------------------------- |
| Red          | ![#f7768e](https://placehold.it/15/f7768e/000000?text=+) `#f7768e` | This keyword, HTML elements, Regex group symbol, Number constants, Terminal Red |
| Orange       | ![#ff9e64](https://placehold.it/15/ff9e64/000000?text=+) `#ff9e64` | Function parameters, Language support constants, Regex character sets |
| Yellow       | ![#e0af68](https://placehold.it/15/e0af68/000000?text=+) `#e0af68` | PHP Globals, Terminal Yellow |
| Yellow Green | ![#9ece6a](https://placehold.it/15/9ece6a/000000?text=+) `#9ece6a` | Strings, CSS class names |
| Green        | ![#73daca](https://placehold.it/15/73daca/000000?text=+) `#73daca` | Object literal keys, Markdown links, Terminal Green |
| Cyan | ![#b4f9f8](https://placehold.it/15/b4f9f8/000000?text=+) `#b4f9f8` | Regex literals |
| Blue green   | ![#2ac3de](https://placehold.it/15/2ac3de/000000?text=+) `#2ac3de` | Language support functions, CSS HTML elements |
| Light blue | ![#7dcfff](https://placehold.it/15/7dcfff/000000?text=+) `#7dcfff` | Object properties, Regex quantifiers and flags, Terminal Cyan, Markdown code, Import/export keywords |
| Blue         | ![#7aa2f7](https://placehold.it/15/7aa2f7/000000?text=+) `#7aa2f7` | Function names, Terminal Blue |
| Purple       | ![#bb9af7](https://placehold.it/15/bb9af7/000000?text=+) `#bb9af7` | Control Keywords, Storage Types, Regex start/end of string, HTML Attributes, Terminal Magenta |
| White        | ![#c0caf5](https://placehold.it/15/c0caf5/000000?text=+) `#c0caf5` | Variables, Terminal White |
| Light Gray   | ![#9aa5ce](https://placehold.it/15/9aa5ce/000000?text=+) `#9aa5ce` | Foreground |
| Black        | ![#24283b](https://placehold.it/15/24283b/000000?text=+) `#24283b` | Background, Terminal Black |

**Comment by enkia** [comment]
Added to readme
