### ISSUE TITLE
Possible to port to JetBrains?

### ISSUE THREAD

**Issue by rafaelcanical** [enkia/tokyo-night-vscode-theme#2]
Are you experienced with JetBrains products? This would be amazing to have there, any plans on that matter?

Thanks

**Comment by enkia** [comment]
Unfortunately, I don’t use any JetBrains IDE’s but I have to say, it would simply be an amazing feeling if someone thought well enough of my theme to bother developing a port for it like people have done for the famous Material and Night Owl themes. :)

Looks like it would be a lot of work, though!

**Comment by rafamrs** [comment]
You know what? I will actually try to do it. https://github.com/rafamrs/tokyo-night-jetbrains-theme

**Comment by Grafikart** [comment]
Here is my first attempt ;) https://github.com/Grafikart/tokyo-night-jetbrains-theme

**Comment by jlram** [comment]
@Grafikart Are you considering developing Night Storm version? If not, I would be glad to fork your project and do so :)

**Comment by Grafikart** [comment]
I do not plan to work on Night Storm so you can fork it or do a pull request.

**Comment by enkia** [comment]
@Grafikart Did you get my comments to your pull request?

**Comment by enkia** [comment]
@Grafikart - Again, your contributions are very much appreciated.

@jlram - That'd be awesome. :)
