### ISSUE TITLE
is this theme MIT licensed ?

### ISSUE THREAD

**Issue by user-mk** [enkia/tokyo-night-vscode-theme#23]
Great theme in my opinion. 

Under which license is this theme ? 

It would be great if you guys could provide a license for it.

**Comment by enkia** [comment]
I put an MIT LICENSE.txt in with it and as long as Microsoft lets me keep using enkia, I suppose it's somewhat legal. However, I'm fine with people using it in any way they wish. 

Why?

**Comment by user-mk** [comment]
Thanks... I just noticed most theme i use in VS Code have an MIT license attached to their Github repo. I did not see yours so i thought let me ask about that.

**Comment by enkia** [comment]
Wow... it's been sitting in the dev all this time, never noticed it wasn't in the repo. Thanks for the heads up, yeesh..
