### ISSUE TITLE
Css curly braces is hardly visible

### ISSUE THREAD

**Issue by mpower02** [enkia/tokyo-night-vscode-theme#24]
There are some issues with the curly braces for css files.  It's like super light yellow and hardly visible until you actually highly the braces.  Anyone else having this problem as well?

Included screenshots:
![Screen Shot 2021-03-06 at 9 27 44 AM](https://user-images.githubusercontent.com/8797822/110215373-47b4f800-7e5e-11eb-9a87-a604a68eb873.png)
![Screen Shot 2021-03-06 at 9 28 46 AM](https://user-images.githubusercontent.com/8797822/110215387-61eed600-7e5e-11eb-9512-52a55bf26841.png)

![Screen Shot 2021-03-06 at 9 29 17 AM](https://user-images.githubusercontent.com/8797822/110215399-716e1f00-7e5e-11eb-8e68-0bebf0e5a55e.png)
![Screen Shot 2021-03-06 at 9 29 41 AM](https://user-images.githubusercontent.com/8797822/110215408-7fbc3b00-7e5e-11eb-96c6-420b384865e8.png)

**Comment by enkia** [comment]
I think you might have [Bracket Pair Colorizer](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer) installed? 

Brackets are shown like this without any extensions installed that modify them:

<img width="367" alt="image" src="https://user-images.githubusercontent.com/255730/110220670-215e7f00-7e95-11eb-9232-887b14f6ba78.png">

**Comment by mpower02** [comment]
@enkia sorry for the late reply.  Currently, I don't have the Bracket Pair Colorizer extensions installed.

![Screen Shot 2021-03-21 at 11 16 15 AM](https://user-images.githubusercontent.com/8797822/111916202-019f8d00-8a37-11eb-91d2-040e076624d9.png)

Any ideas on other extensions that might be causing this issue?  Thanks!

**Comment by enkia** [comment]
Hmm, put your cursor right before the offending bracket, open the command palette and type `inspect editor token` and screenshot what pops up.

**Comment by mpower02** [comment]
Here's a screenshot:
![Screen Shot 2021-03-24 at 9 21 56 AM](https://user-images.githubusercontent.com/8797822/112345702-803c3a80-8c82-11eb-8885-acb04d5a4717.png)

**Comment by enkia** [comment]
Welp, the foreground color is right so my theme is all good. I searched around and couldn't find any other extension that would change those parenthesis and brackets... 17K+ line file, though? Maybe vscode is dying under the load. :) 

Also, you took a screenshot of your extension list and that's not any of my theme's UI colors so there's that too. 

Anyway, I doubt I can be of help.
