### ISSUE TITLE
the selection color is too light to recogonize

### ISSUE THREAD

**Issue by tjx666** [enkia/tokyo-night-vscode-theme#25]
![image](https://user-images.githubusercontent.com/41773861/111615990-53b89680-881c-11eb-9843-26fa3f04f25c.png)

**Comment by enkia** [comment]
Does pasting this into your settings.json help?

```
    "workbench.colorCustomizations": {
        "[Tokyo Night Storm]": { // Name of theme
            "editor.wordHighlightBackground": "#6f7bb644",
            "editor.wordHighlightStrongBackground": "#6f7bb655",
            "editor.selectionHighlightBackground": "#6f7bb633",
      }
```

**Comment by tjx666** [comment]
@enkia 
![image](https://user-images.githubusercontent.com/41773861/111737343-6bdef300-88ba-11eb-9081-b7ab1f6597b4.png)

**Comment by enkia** [comment]
You can modify the colors to suit your personal preference by editing the settings I provided. 

See [color formats](https://code.visualstudio.com/api/references/theme-color) in Vscode’s api reference.
