### ISSUE TITLE
Vertical pipe being displayed in italics making it seem like a forward slash

### ISSUE THREAD

**Issue by kpenergy** [enkia/tokyo-night-vscode-theme#27]
I'm creating an AWS Cloud Formation template in YAML, and I've noticed that for some reason a vertical pipe is being displayed in italics, making it seem like it's a forward slash. 

![image](https://user-images.githubusercontent.com/79311819/112146843-f3d33e80-8bd3-11eb-83bf-b772b1cfff4e.png)

I have `ZipFile: |`, but it looks like `ZipFile: /` and is a little confusing. 

For comparison, here is a forward slash next to it. 

![image](https://user-images.githubusercontent.com/79311819/112147277-6ba16900-8bd4-11eb-8b22-724e7dfa4c95.png)

I cant figure out what setting is causing this so I'm not sure how to fix it. Are you able to help at all?

Thanks!

**Comment by enkia** [comment]
Interesting... the pipe is considered a control flow keyword like _return._ I've specifically set yaml's multi-line scalar symbol to normal for yaml files. In a few minutes, the latest version will reflect the fix.
