### ISSUE TITLE
Integrated terminal font colors hard to see on background

### ISSUE THREAD

**Issue by Perdyx** [enkia/tokyo-night-vscode-theme#3]
![image](https://user-images.githubusercontent.com/29049651/78846708-7bbf3900-79c1-11ea-9f15-d828c986f8eb.png)
![image](https://user-images.githubusercontent.com/29049651/78846735-9beef800-79c1-11ea-94d8-1c8128df13b1.png)

**Comment by enkia** [comment]
If I fix the ansiWhite to be pure white, thus fixing your issue, the true white won't conform to the 'white' I'm using throughout the theme. The designer in me conflicts with the coder in me in this case.  I'll have to give this fix some thought. For now, in order to fix your issue, add this to your settings.json for my theme:

```
"workbench.colorCustomizations": {
    "[Tokyo Night]": {
        "terminal.ansiBrightWhite": "#ffffff",
        "terminal.ansiWhite": "#ffffff"
    }
}
```

**Comment by Perdyx** [comment]
Thank you so much! Best of luck figuring out the colors.

**Comment by DogeCPU** [comment]
Did you customize it? You might want to try running bash in VSCode with this theme newly installed.

**Comment by enkia** [comment]
@Perdyx, hmm try adding `"terminal.foreground": "#ffffff"` to the list of customizations.

**Comment by DogeCPU** [comment]
Is this Tokyo Night or Tokyo Night Storm? It looks like Night Storm. That would be useful if you are implementing a fix.

**Comment by enkia** [comment]
Indeed, I should have been more specific. Change `"[Tokyo Night]": {` to reflect the name of the theme being modified.

**Comment by Perdyx** [comment]
Yeah I tried changing the theme name in there and setting the terminal foreground color and neither did anything... The issue happens when you run a NodeJS file (node app.js) with a reference error if you need something to test it with.

**Comment by Perdyx** [comment]
I did some playing with it and narrowed it down to the DarkGrey colour. If it doesn't cause too many issues in the normal syntax highlighting, I would suggest maybe changing that to something a little lighter... Let me know if you have questions/what you think.

**Comment by Perdyx** [comment]
Fixed it by changing setting `"terminal.ansiBrightBlack": "#ffffff"` in my `settings.json`.

![image](https://user-images.githubusercontent.com/29049651/79024324-73890a00-7b37-11ea-83d9-a3eaca10fd45.png)

**Comment by enkia** [comment]
Yeah, I completely misunderstood your original post as I was reading it on a very dimmed iPhone screen and didn't even see the black text in your screenshot and saw the glaring light blue on red text!

Anyway, some output uses ansiblack for the purpose of black. For example:

<img width="348" alt="image"  title="DONE" src="https://user-images.githubusercontent.com/255730/79047175-1480cf00-7be3-11ea-8c2d-bddede7c51a4.png">

If I change black to be lighter, then it's unreadable in other areas. However, maybe those use cases aren't as wide spread as your own. I've updated the two dark themes' terminal black to their line number foreground color as per your suggestion.

**Comment by CodeMacabre** [comment]
I use Tokyo Night Storm's terminal colours in my Window Terminal and noticed that the brightBlack was a little too unreadable. I've updated both the VS Code scheme and Terminal to be `#414868` instead (+5% brightness, -5% contrast, -5% saturation) which is a subtle enough increase in brightness to fit nicely with the rest of the theme.

I'm happy to put in a PR if you'd like this update?

**Comment by enkia** [comment]
@CodeMacabre Thanks! I've made an update to Tokyo Night Storm to use #414868.
