### ISSUE TITLE
Support for Visual Studio?

### ISSUE THREAD

**Issue by glibg10b** [enkia/tokyo-night-vscode-theme#31]
I really love this theme. It's the best high contrast, high saturation theme I could find so far. Do you think you could port it to Visual Studio? I was really disappointed to find it isn't there :(

**Comment by kotx** [comment]
I hear that making themes for VS is a pain, but it would be nice lol

**Comment by enkia** [comment]
Won't be any support from me for it, sadly..

**Comment by kotx** [comment]
Sounds reasonable. If you ever do decide to do it though, [this](https://github.com/microsoft/theme-converter-for-vs) may help.

**Comment by m1chaelbarry** [comment]
https://github.com/m1chaelbarry/tokyo-night-visual-studio-theme

**Comment by glibg10b** [comment]
@m1chaelbarry Wow, well done!

**Comment by glibg10b** [comment]
Not sure why I didn't close this before lol
