### ISSUE TITLE
Comments are too much dark

### ISSUE THREAD

**Issue by Bhaskar-Khoraja** [enkia/tokyo-night-vscode-theme#33]
The comment's color are too much close too the background color hence, comment are hard to read. Making comment color grey or and other color that doesn't match the background color would be excellent.

**Comment by cheesecakeassassin** [comment]
I agree and came here looking for the same exact issue.

**Comment by enkia** [comment]
Both of you are right and I'm sure a good percentage of people have changed the comment color in their settings for it. There are some things about the theme, like the comments, that I knew wouldn't be popular (hence the note at the top of the readme) but I didn't seek to make a popular theme neccessarily, just one that I like. I published it in case others had my same tastes and added instruction to the README on how to tailor the colors for it and all themes which I think is fair enough. :)
