### ISSUE TITLE
bracket pair colourisation support

### ISSUE THREAD

**Issue by tauin** [enkia/tokyo-night-vscode-theme#37]
vscode recently added office bracket pair colourisation with theming, would it be possible to update this theme to reflect colour the brackets correctly

**Comment by enkia** [comment]
After many months (apologies), I finally added bracket pair theme colors. 

**Beta Disclaimer:** I don’t use bracket pair colorization… could never quite get used to it. This is probably going be a work in progress. Provided I get enough feedback, we may end up with something decent. :)
