### ISSUE TITLE
differences between *.js and *.ts

### ISSUE THREAD

**Issue by drcmda** [enkia/tokyo-night-vscode-theme#4]
First of all, this theme is truly awesome. I think i have finally discovered something that i want to stick with.

Just a minor thing, i would much prefer how it colors typescript files, especially imports

<img width="988" alt="Screenshot 2020-04-11 at 18 52 51" src="https://user-images.githubusercontent.com/2223602/79049739-add0d500-7c25-11ea-9974-905e55deacb4.png">

over all the purple in javascript files

<img width="1000" alt="Screenshot 2020-04-11 at 18 49 05" src="https://user-images.githubusercontent.com/2223602/79049645-27b48e80-7c25-11ea-9754-a77c60e1c54c.png">

Is there a reason it's doing this? Can it be configured?

**Comment by enkia** [comment]
Hmm, I'm not getting purple import statements from js files... Also, it looks like you're using Bracket Pair Colorizer extension in the second screenshot which would explain the pink brackets, and such. 

Try searching for `@installed javascript syntax` in extensions ... using any non default defs?

Also, set the cursor on the word `import` in a js file and run the command 'Inspect Editor Tokens and Scopes'. Can you paste what pops up?

**Comment by drcmda** [comment]
Thanks, that was it! Something called "babel sublime syntax" don't even remember having installed it.

**Comment by enkia** [comment]
Glad I could help! And thanks for the kind words about my theme.
