### ISSUE TITLE
Font used in example pictures

### ISSUE THREAD

**Issue by kleenkanteen** [enkia/tokyo-night-vscode-theme#40]
What font are those?

**Comment by vaelu** [comment]
Same question here, hehe. @enkia

**Comment by edi2004** [comment]
I think it's the same as the original theme Enki, "Operator Mono"
https://github.com/enkia/enki-theme#notes

**Comment by vaelu** [comment]
Yeah, Jetbrains Mono looks like the font on the screenshots. Thanks!
