### ISSUE TITLE
Python match, case not highlighting

### ISSUE THREAD

**Issue by layzduck** [enkia/tokyo-night-vscode-theme#41]
Hello, I have noticed that the match-case keyword in Python is not highlighting up. An image relating to that issue is down below. I hope that will help you fix it. 
Thank you for the awesome theme as well!!

<img width="217" alt="Screenshot 2022-01-07 at 4 45 55 PM" src="https://user-images.githubusercontent.com/88228849/148509815-3f509733-c2c3-44c2-99b3-5ea40c43b372.png">

**Comment by enkia** [comment]
It appears that there isn't a text mate scope for that. All themes seem to suffer the same issue?
