### ISSUE TITLE
Better zen mode colouring?

### ISSUE THREAD

**Issue by jasonkuhrt** [enkia/tokyo-night-vscode-theme#43]
![CleanShot 2022-02-19 at 12 56 51@2x](https://user-images.githubusercontent.com/284476/154812988-646e77fb-9a4e-4861-bb66-0e03bea0370d.png)

In Zen mode the contrast between the file and the surrounding UI seems undesirable?

**Comment by enkia** [comment]
I'm not willing to change that since I like it, but I also don't think there's anything that allows for specific zen mode bg theme settings.
