### ISSUE TITLE
Function parameters color inconsistent 

### ISSUE THREAD

**Issue by sivan-taranis** [enkia/tokyo-night-vscode-theme#47]
![image](https://user-images.githubusercontent.com/98332084/159880756-e29bd0fb-0ce6-4ab3-9b5c-9ae7aad02ae8.png)

I find this situation sub-optimal. I think it might be more pleasant to much the functions parameter on definition/declaration and on function calls. While maybe modifying the color of 'None' just a little bit to make it distinguishable.

All in all this is my favorite theme in time! Thanks a lot for this creation.

**Comment by enkia** [comment]
It's optimal as far as what I prefer to see. First are function parameters and the other is the color of a constant value. 

However, you can change the constant to something more obvious using:

```
"editor.tokenColorCustomizations": {
    "[Tokyo Night]": { // or "[Tokyo Night Storm]"
        "textMateRules": [{
            "scope":  "constant.numeric",
            "settings": {
                "foreground": "#9ECE6A" // preferred color
            }
        }]
    }
}
```

This will change the color of constants to green. 

Apologies for the late reply!

**Comment by sivan-taranis** [comment]
I agree, TY for the response!
