### ISSUE TITLE
Github Organization for Tokyo Night

### ISSUE THREAD

**Issue by FosterHangdaan** [enkia/tokyo-night-vscode-theme#48]
I have created a Github Organization for Tokyo Night [here](https://github.com/tokyo-night). It will be organized and managed similar to the organizations for the [Catppuccin](https://github.com/catppuccin) and [Dracula](https://github.com/dracula) themes.

An organization will be a great way to consolidate all the Tokyo Night theme repos into one place. I thought it would help in making the Tokyo Night theme gain more popularity.

I'd like to know if there's interest in having such an organization. I'd gladly help in managing and maintaining it.

**Comment by enkia** [comment]
Are you saying I'm not keeping up on my pull requests? :)

**Comment by enkia** [comment]
I'm interested, but am hesitant to transfer(?) this repo to that organization that I am not the official owner of. I have to admit that I'm not familiar with how GitHub organizations work. I'm not even sure if I need to be 'hesitant.' Can I 'own' it and provide you moderator level of access to it?

**Comment by FosterHangdaan** [comment]
Github organizations can have multiple owners.

I have sent you an invite. I will grant ownership role to you once you accept.
