### ISSUE TITLE
Request for Terraform Keyword Support

### ISSUE THREAD

**Issue by karthikrao5** [enkia/tokyo-night-vscode-theme#50]
Love the theme, but it doesn't really work well for terraform syntax. Keywords are not separated from variable name colors, see screenshots. Notice how "resource" and "ingress" are not different colors than the variable "aws_security"group"

<img width="546" alt="Screen Shot 2022-04-25 at 4 43 08 PM" src="https://user-images.githubusercontent.com/10218590/165171737-e922a721-554f-4556-b187-8ecb4347d7c8.png">
<img width="550" alt="Screen Shot 2022-04-25 at 4 42 54 PM" src="https://user-images.githubusercontent.com/10218590/165171738-63b8ae4e-4f9b-49ff-8940-3079f810a041.png">

**Comment by enkia** [comment]
Apologies for the late response. I've added preliminary support for Terraform syntax, but I don't know the language so I'm flying a bit blind. Provide feedback if needed, thanks!
