### ISSUE TITLE
Vue files does not fully support

### ISSUE THREAD

**Issue by antoniogiroz** [enkia/tokyo-night-vscode-theme#51]
Hi!

Vue template directives are not colorized as native HTML attributes.

![SCR-20220503-eu5](https://user-images.githubusercontent.com/520071/166426153-c3836a43-93a1-4adc-8a1b-cf3a98498577.png)

How could I customize these things in the Tokyo Night theme?

Thanks a lot!

**Comment by enkia** [comment]
I can't replicate the issue with Vetur or Volar installed?
