### ISSUE TITLE
Colors are not rendered anymore

### ISSUE THREAD

**Issue by vandadnp** [enkia/tokyo-night-vscode-theme#54]
Hi and thank you for this absolutely beautiful theme

I've noticed that the colors are not rendered anymore in any browser please see attached

<img width="430" alt="image" src="https://user-images.githubusercontent.com/759524/171784603-afc2c94a-d22e-4d02-88ef-abb761115ab9.png">

**Comment by enkia** [comment]
Merging #53 soon, thanks.
