### ISSUE TITLE
Scrollbar color

### ISSUE THREAD

**Issue by mapsgeek** [enkia/tokyo-night-vscode-theme#58]
Scrollbar color is missed up for themes altsynt and gogh but fine for the just night and night storm.
tried uninstalling/reinstalling, different versions! it didn't use to look like that.

![image](https://user-images.githubusercontent.com/10188264/178649343-494899b2-b61d-4f2c-944f-6ce6fa640dde.png)
![image](https://user-images.githubusercontent.com/10188264/178649386-f5348bfe-20f1-4cbf-bdd5-f6e3cbbaffb4.png)

**Comment by enkia** [comment]
Do you have anything with `editorOverviewRuler.background` in your settings.json?

**Comment by mapsgeek** [comment]
@enkia nope, should i add it under `colorCustomizations` ?
isn't supposed to be provided by the theme?

**Comment by enkia** [comment]
You could try that but it shouldn't be necessary. Vscode uses the editor.background color if the editorOverviewRuler.background color isn't specified and *only* if you have minimal enabled which you don't. 

I'm not sure what is causing the issue, but this is the first issue referencing it so I doubt it's my theme. Many themes don't specify the color either such as OneDark-Pro, Night Owl, etc. I also notice that the [latest release of vscode](https://code.visualstudio.com/updates/v1_69) added a shell integration feature to the overview ruler area so it may have something to do with that.

**Comment by mapsgeek** [comment]
hmm not really sure, all other themes are just fine and this happens only with the mentioned themes

**Comment by enkia** [comment]
"Tokyo Storm AltSynt" isn't my theme.

**Comment by mapsgeek** [comment]
ok sorry thought that it's the same theme.
