### ISSUE TITLE
Poor contrast for merge conflict text

### ISSUE THREAD

**Issue by karbica** [enkia/tokyo-night-vscode-theme#60]
When merge conflicts occur, the builtin VSCode merge conflict helper has poor contrast making the "Current Change" and "Incoming Change" hard to read.

<img width="549" alt="Screen Shot 2022-08-02 at 11 13 29 AM" src="https://user-images.githubusercontent.com/8563742/182445356-113dd864-adc8-4712-9158-976fcc335b51.png">

I'm thinking that the text match the background color so it "punches" through the green and blue bars.

<img width="544" alt="Screen Shot 2022-08-02 at 11 20 55 AM" src="https://user-images.githubusercontent.com/8563742/182446056-d78ee3d0-8c85-43b3-8c17-14b2f5a0ae75.png">

Or lighten the text based on the background color for each.

<img width="542" alt="Screen Shot 2022-08-02 at 11 27 16 AM" src="https://user-images.githubusercontent.com/8563742/182447145-3b4c9156-6b85-4f17-a633-dce3a8a48f92.png">

Using the following colors:

`#10a6a4`
`#5772b9`

Or if there is a better color that follows the theme, that would be preferred.

**Comment by enkia** [comment]
I agree, but never found the ability to change that color. I don't see it listed in the [reference](https://code.visualstudio.com/api/references/theme-color#merge-conflicts-colors) either. 

Is it possible for you to upgrade Vscode to the latest? This should solve the issue with their new 3 way merge UI.
