### ISSUE TITLE
Python 3.10 "match/case" highlighting doesn't work

### ISSUE THREAD

**Issue by SirZokxyron** [enkia/tokyo-night-vscode-theme#64]
# Issue
When writing python 3.10+ the `match` and `case` keywords are not highlighted.
I've provided screenshots to compare with the default dark VS Code theme.

# Expected `match`/`case` highlighting
![default](https://user-images.githubusercontent.com/25960628/195605166-560e8a9a-5c1c-46ca-aa20-f7eae0a552db.png)

# Actual `match`/`case` highlighting
![tokyonight](https://user-images.githubusercontent.com/25960628/195605181-07ea0b93-d5ef-4772-b63c-bb335daabb93.png)

# Suggested `match`/`case` highlighting
![suggestion](https://user-images.githubusercontent.com/25960628/195605838-0f97ebb1-a501-4fa4-bc24-b74f2ee6d663.png)
Since `match` and `case` are two regular keywords, it'd be logical to apply the same color as `if`, `else`, etc.

Thank you for your time, and thank you again for this wonderful theme!

**Comment by enkia** [comment]
Apologies for the late response. I can't seem to replicate on my end? if/else, match/case, switch, etc uses textmate scope keyword.control which is in my theme.  I don't write python scripts so I may be missing something. I'm using the Python extension by Microsoft. 

<img width="390" alt="image" src="https://user-images.githubusercontent.com/255730/202500994-a7e719ea-d7a0-47ca-aa2f-5b79846b8735.png">

**Comment by SirZokxyron** [comment]
Well, for some magic reasons, it works now.
Perhaps something has been updated somewhere, or I had something badly configured, I have no idea.

Anyway, thanks for the reply, I'm closing the issue.

Have a nice day!
