### ISSUE TITLE
Colour from custom component is the same as regular HTML tags

### ISSUE THREAD

**Issue by Rem0ld** [enkia/tokyo-night-vscode-theme#66]
<img width="500" alt="image" src="https://user-images.githubusercontent.com/60188728/203946533-9a770028-e244-48c4-8d36-ecfe097855a7.png">

As you can see on the picture when we use Login and Register components there're exactly the same colour as other html tags.
It can be difficult to see what is what.

<img width="463" alt="image" src="https://user-images.githubusercontent.com/60188728/203954020-335f3cd4-6849-44bd-812b-150f5487fed6.png">

With this theme we can see the difference.

Could it be possible to add the same behaviour?

**Comment by denys-petryniak** [comment]
The following only works for React, doesn't work for Vue templates unfortunately

`  "editor.tokenColorCustomizations": {
    "[Tokyo Night]": {
      "textMateRules": [
        {
          "name": "JSX/TSX Component tags",
          "scope": ["entity.name.tag support.class.component"],
          "settings": { "foreground": "#00fab5" }
        }
      ]
    }
  },`

**Comment by CubW0lf** [comment]
Is it a way for punctuation.definition.tag too? I already get tags differenciated but not for begin or end closing tag color difference.
<img width="522" alt="Capture d’écran 2022-12-23 à 15 14 59" src="https://user-images.githubusercontent.com/81014220/209349956-b7ef6024-62a0-4a19-b363-1ad833ffc4db.png">

As you can see the components are greenish and the html tag are blueish but the opening and closing tag stay blue...

**Comment by enkia** [comment]
The latest version fixes the issue with Volar.
