### ISSUE TITLE
Customizing tag colours

### ISSUE THREAD

**Issue by jamesthomsondev** [enkia/tokyo-night-vscode-theme#67]
I notice the element tag colours have changed. I'm not a fan and would like to revert it back to the original. I see here is the change: https://github.com/enkia/tokyo-night-vscode-theme/blob/ab23a44d8984583727943d1c3637924da6eab66c/themes/tokyo-night-storm-color-theme.json#L693

How can I customise this myself?

**Comment by jamesthomsondev** [comment]
If anyone comes across this, figured it out as adding this to your `settings.json`

```
"editor.tokenColorCustomizations": {
    "[Tokyo Night Storm]": {
      "textMateRules": [
        {
          "name": "Tag - Custom",
          "scope": [
            "entity.name.tag support.class.component",
            "meta.tag.custom entity.name.tag",
            "meta.tag"
          ],
          "settings": {
            "foreground": "#de5971"
          }
        }
      ]
    }
  },
```

**Comment by enkia** [comment]
Hey all, I reverted this color change I made to the dark themes. I had temporary insanity!

@jamesthomsondev Thanks, people who want them more obvious will appreciate that snippet.

**Comment by AshConnolly** [comment]
Thank you @enkia for reverting! 
Releasing your revert whilst I was implementing my own revert (same as @jamesthomsondev code above) really had my confused! 😄

**Comment by jamesthomsondev** [comment]
@enkia Didn't mean to make you doubt your decision, I just found it jarring when my element tags were very bright all of a sudden 😄 Really appreciate the work you've put into this theme, it's by far my favourite 🙏

**Comment by AshConnolly** [comment]
Yeh echoing @jamesthomsondev, thanks so much @enkia, this Storm variant is the best theme I've seen in years! 😄
