### ISSUE TITLE
Highlight background color too subtle

### ISSUE THREAD

**Issue by samholmes** [enkia/tokyo-night-vscode-theme#69]
<img width="268" alt="Screen Shot 2023-03-02 at 1 34 10 PM" src="https://user-images.githubusercontent.com/517469/222560863-8102ecd2-d9e6-4d84-99fb-2f5fd16dc7d2.png">
<img width="189" alt="Screen Shot 2023-03-02 at 1 34 20 PM" src="https://user-images.githubusercontent.com/517469/222560898-c34f438c-59d9-43bb-a5a8-3e8cce3f3d79.png">

I've highlighted the word "hello" in the second image, but the highlight is too faint to notice. Why is this happening?

**Comment by samholmes** [comment]
I fixed it with this:

```
  "workbench.colorCustomizations": {
    "editor.selectionBackground": "#135564",
    "editor.selectionHighlightBackground": "#135564",
    "terminal.selectionBackground": "#135564"
  },
  ```

<img width="305" alt="Screen Shot 2023-03-02 at 1 36 47 PM" src="https://user-images.githubusercontent.com/517469/222561302-e1bb8f82-b84c-43bb-bf0c-548785bd18bc.png">

  
Shouldn't this be committed upstream? (preferably with a color from the theme's palette)

**Comment by samholmes** [comment]
> I've increased it _slightly_ since this issue has come up in the past. However, based on your screenshots, you might decide your settings are preferable.

What does it look like?

**Comment by enkia** [comment]
<img width="306" alt="image" src="https://user-images.githubusercontent.com/255730/226722392-b3d1fdf0-836e-4f14-aea0-7ed7c089ec6a.png">

<img width="388" alt="image" src="https://user-images.githubusercontent.com/255730/226722410-3089d395-2dc8-4ec5-87c7-88e754198791.png">
