### ISSUE TITLE
Converting theme to Eclipse

### ISSUE THREAD

**Issue by the-reminisce** [enkia/tokyo-night-vscode-theme#7]
Is there anyway that you could convert this theme to eclipse! This theme is bloody beautiful, you honestly did such an amazing job on it! Great work!
http://www.eclipsecolorthemes.org/
That's the site for eclipse themes. Please <3 I'm obsessed with your theme now!

**Comment by the-reminisce** [comment]
Maybe for intellij as well? <3

**Comment by mikkhimself** [comment]
+1

**Comment by enkia** [comment]
Just FYI, I haven't ignored this ticket but I have to give this some thought. I don't use either IDE. :)

**Comment by the-reminisce** [comment]
> 
> 
> Just FYI, I haven't ignored this ticket, but I have to give this some thought. I don't use either IDE. :)

@enkia Thank you :) I had to make my own sloppy incomplete version of your theme for eclipse, but it just doesn't look the same :(
![image](https://user-images.githubusercontent.com/53870047/89756298-1040c180-dab0-11ea-9f95-bb4742101f86.png)

**Comment by enkia** [comment]
@the-reminisce 

Looks pretty good. :) I don't think I can provide much help or ever have the time to discover the wonder that is Java so I'm going to go ahead and close this.
