### ISSUE TITLE
Colors seem a bit off

### ISSUE THREAD

**Issue by CarlosCB1986** [enkia/tokyo-night-vscode-theme#71]
<img width="429" alt="image" src="https://user-images.githubusercontent.com/20017165/227022829-45106282-14be-424a-a470-6ed4b10f790f.png">

The below piece of code does not seem to have consistent colors:
`const exampleFunction = (
    example: string[]
  ): {
    example: Map<string, number>;
    test: Set<string>;
    another: Array<{ siteId: string; cveId: string }>;
  } | null => null`

This is using tokyo night storm v0.9.8 in Visual code 1.76.2

**Comment by enkia** [comment]
Try enabling semantic highlighting:    
`"editor.semanticHighlighting.enabled": true,`

**Comment by CarlosCB1986** [comment]
Tried it but I still see incoherences. The closing character > is still red but the opening < is not which does not seem to be correct.
