### ISSUE TITLE
Add a mention of Enki-Tokyo-Night.tmTheme

### ISSUE THREAD

**Issue by Lassebq** [enkia/tokyo-night-vscode-theme#74]
https://github.com/enkia/enki-theme/blob/master/scheme/Enki-Tokyo-Night.tmTheme
Even though tmThemes have been deprecated for sublime text, it seems that [bat](https://github.com/sharkdp/bat) still uses them.
I had trouble finding a theme for bat, It'd be nice if you could include it in [Other ports](https://github.com/enkia/tokyo-night-vscode-theme#other-ports) :3

**Comment by Lassebq** [comment]
Oh wait, I just noticed it's mentioned in README, Though it doesn't say that it can be used with bat. Can you add that please?

**Comment by enkia** [comment]
Yep, will update readme to "**Sublime Text / bat**"
