### ISSUE TITLE
[Question] Is there a way to make the colors the same as Tokyo night in Neovim?

### ISSUE THREAD

**Issue by ok97465** [enkia/tokyo-night-vscode-theme#77]
Hello and thank you for creating such a great extension.

I've been using Tokyonight in Neovim for a long time.

![이미지 2023  7  27  오전 12 32](https://github.com/enkia/tokyo-night-vscode-theme/assets/22970578/6fcd6fe6-305a-4498-b9bb-9e2d17242e60)

The picture on the left is the result of Vscode's Python syntax highlight and the picture on the right is the result of Neovim.

Quotes, Class, augments, etc. have different colors, is there any way to make them the same?

Thank you.

**Comment by enkia** [comment]
Using either MagicPython or Python extensions, I'm not seeing enough specificity with textmate scopes to turn some of those functions purple, or log_dir green as it's specified as any other argument, or how the variable declarations are just plain source.python. 

I also don't work with Python so I may be missing something. For example, `bustruck_df2img_info` and `BusTruckDataModuleFasterRCNN` show the same meta.function-call scopes.

With that said, I noticed a few improvements that I can do... thoughts?

<img width="678" alt="image" src="https://github.com/enkia/tokyo-night-vscode-theme/assets/255730/d2750440-a9d8-48f6-86c7-f4598b8f0d71">
