### ISSUE TITLE
JS React red font

### ISSUE THREAD

**Issue by QuentinVdr** [enkia/tokyo-night-vscode-theme#78]
Hello,
I get red font color in my react component when I'm not using tsx. Is that normal or a bug?
![image](https://github.com/enkia/tokyo-night-vscode-theme/assets/56938113/8f8dbc08-0db3-4bc5-a4fe-5ae256954dba)

**Comment by DonMiller9294** [comment]
it could the syntax or color scheme based on the theme you are using. have your ran the code? is every working?

**Comment by QuentinVdr** [comment]
In my screenshot it's just the code from a default react project by using `npx create-react-app`. And I modify your theme just by adding the `Higher Contrast Settings` that you recommend in the README and add the rulers. And Even without my settings I get the color font in red.

**Comment by enkia** [comment]
It's not normal, should be white gray color. Can you place your cursor at the word save and run 'Inspect Editor Tokens and Scopes' from the command palette and paste the result here?

**Comment by QuentinVdr** [comment]
here's the screenshot and the text of the Inspect Editor Tokens and Scopes. 
if you want to check is just a default react app create with `npx create-react-app my-app`.
![image](https://github.com/enkia/tokyo-night-vscode-theme/assets/56938113/e990aac5-f2b8-4ed0-b49b-355fe9f7172b)

<html>
<body>


language | jsx
-- | --
standard token type | Other
foreground | #DE5971
background | #1A1B26
contrast ratio | 4.70


</body>
</html>
<html>
<body>


textmate scopes | JSXNested JSXAttrs meta.tag.jsx JSXNested JSXAttrs meta.tag.jsx JSXNested JSXAttrs meta.tag.js xmeta.function.js source.js
-- | --
foreground | meta.tag{ "foreground": "#DE5971" }


</body>
</html>

**Comment by enkia** [comment]
Hmm, can't replicate the issue. Must be an extension or the theme isn't actually mine, but a fork / mod. The brackets on the HTML tags are even different. Mine look like this:

<img width="586" alt="image" src="https://github.com/enkia/tokyo-night-vscode-theme/assets/255730/1dbeca89-aa36-4be3-9a20-d8f1bc390ad6">

I did notice that regular jsx text is a bit bright (white) so will push a fix for that, though.

**Comment by QuentinVdr** [comment]
It's my bad i found why it's don't work like usual.
It's cause i use `Babel javascript` extension.
I don't know if you have planned to support this syntax highlighting or not ?

**Comment by enkia** [comment]
All good. It looks pretty well supported aside from the issue you saw and a couple other things I noticed. I've pushed a fix! Let me know how it works out.

**Comment by QuentinVdr** [comment]
Thanks you a lot! 
Your job is really nice. Love it!
