### ISSUE TITLE
Menus are not legible over Light theme

### ISSUE THREAD

**Issue by javlaks** [enkia/tokyo-night-vscode-theme#8]
### There is an issue when the Tokyo Night Light theme is selected. 

When the mouse is over a menu item (hover), this menu is not legible

This over the menu bar
![image](https://user-images.githubusercontent.com/513351/89746693-b07ef200-da80-11ea-84da-a63075ccf913.png)

This is over the settings
![image](https://user-images.githubusercontent.com/513351/89746705-bd034a80-da80-11ea-9ae4-9467ac457bc0.png)

### Expected behavior
The font foreground should change to a lighter color to be visible

**Comment by enkia** [comment]
Thanks, I've published a fix for this.
