### ISSUE TITLE
Terminal green doesn't match between Night and Storm versions

### ISSUE THREAD

**Issue by Lassebq** [enkia/tokyo-night-vscode-theme#80]
Title is self explanatory

**Comment by enkia** [comment]
Thanks for the heads up! Pushed a fix.

**Comment by Lassebq** [comment]
![image](https://github.com/enkia/tokyo-night-vscode-theme/assets/68742864/9054f4e3-c7b4-4a6b-bb2f-18b91cb4e781)
There's still a problem, only regular green was fixed. Light green remained unchanged

**Comment by hydrajump** [comment]
Didn't see this issue before I created a similar one https://github.com/tokyo-night/tokyo-night-vscode-theme/issues/99#issue-2785001954
