### ISSUE TITLE
Add moon theme

### ISSUE THREAD

**Issue by robsonpeixoto** [enkia/tokyo-night-vscode-theme#91]
This plugin is amazing! Thanks ❤️ 

Please add [moon](https://github.com/folke/tokyonight.nvim/blob/81c867c5f638597a82c82094dcb90ed42444dabc/lua/tokyonight/colors.lua#L51-L96) color.

**Comment by enkia** [comment]
Take someone else's color variation? No inclination to do that, but I appreciate that you like my theme!

**Comment by Arvid-G** [comment]
He is refereing to the neovim port of your theme. It has the day night and storm variant, but also added a moon variant which is in between of storm and night. So a bit less dark than night but still great contrast (higher than storm). It became the default for many neovim users and the dude made very many ports (see: https://github.com/folke/tokyonight.nvim/tree/main/extras ), likely this is why he was asking for this.
See for yourself: https://github.com/folke/tokyonight.nvim

PS: nice theme ;) thx!
